import { env } from 'cloudflare:workers';
import { boundedScout,ScoutError } from '../../../lib/scout';
import { getChatGPTUser } from '../../chatgpt-auth';
import { database } from '../../../db';
import {AppError,getOwner,saveSchema,publicProfile,eligibleProfiles,requireActive} from '../../../lib/server';
import {demoProfiles,demoRecommendation} from '../../../lib/demo';
import type {Profile,ScoutRun,Intention} from '../../../lib/types';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function visibleRun(run:ScoutRun,uid:string):Promise<ScoutRun>{if(run.mode==='demo')return run;const owner=await getOwner(uid);if(!owner)return {...run,status:'empty',shortlist:[],profiles:[]};const current=(await eligibleProfiles(uid,owner,run.intention)).filter(c=>c.settings.allowEvidence).map(c=>publicProfile(c.profile));const shortlist=run.shortlist.filter(r=>{const p=current.find(p=>p.id===r.candidateId),old=run.profiles.find(p=>p.id===r.candidateId);const projection=(p:Profile)=>JSON.stringify(p.evidence.filter(e=>e.visible&&e.scoutUse).slice(0,5).map(e=>({id:e.id,kind:e.kind,title:e.title,description:e.description.slice(0,600),value:e.value??null,unit:e.unit||'',coverage:e.coverage||'',asOf:e.asOf,provenance:e.provenance})));return p&&old&&projection(p)===projection(old)&&r.reasons.every(reason=>reason.evidenceIds.every(id=>p.evidence.some(e=>e.id===id&&e.visible&&e.scoutUse)));});return {...run,status:shortlist.length?'complete':'empty',shortlist,profiles:current.filter(p=>shortlist.some(r=>r.candidateId===p.id))};}
async function handle(req:Request){try{
 const user=await getChatGPTUser();const path=new URL(req.url).pathname.replace(/^\/api\//,'');const method=req.method;
 if(path==='session'&&method==='GET')return json({authenticated:!!user,displayName:user?.fullName||null,authProvider:'ChatGPT',runtime:'Sites dispatch-owned SIWC',liveScoutAvailable:!!env.OPENAI_API_KEY});
 if(!user)throw new AppError('SIGN_IN_REQUIRED','Sign in with ChatGPT to continue.',401);
 if(method!=='GET'){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new AppError('ORIGIN_REJECTED','This action must start from this app.',403);}
 const db=database();const now=new Date().toISOString();const uid=user.userId;
 if(path==='me'&&method==='GET')return json({owner:await getOwner(uid)});
 if(path==='me'&&method==='PUT'){
  const raw=await req.json();const parsed=saveSchema.safeParse(raw);if(!parsed.success)throw new AppError('INVALID_PROFILE',parsed.error.issues.map(x=>x.message).join(' '));
  const existing=await getOwner(uid);const {profile,settings}=parsed.data;
  if(profile.mode==='live'&&profile.status==='available'&&!settings.discoveryConsent)throw new AppError('CONSENT_REQUIRED','Approve discovery before joining the directory.');
  if(!profile.intentions.includes(settings.selectedIntention))throw new AppError('INTENTION_REQUIRED','Your active intention must be one you selected.');
  const id=existing?.profile.id||crypto.randomUUID();const clean:Profile={...profile,id,status:profile.mode==='demo'?'demoOnly':profile.status,evidence:profile.evidence.map(e=>({...e,provenance:'ownerSupplied'}))};
  await db.prepare('INSERT INTO profiles (account_id,profile_id,data,settings,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(account_id) DO UPDATE SET data=excluded.data,settings=excluded.settings,updated_at=excluded.updated_at').bind(uid,id,JSON.stringify(clean),JSON.stringify({...settings,updatedAt:now}),now).run();return json({owner:{profile:clean,settings:{...settings,updatedAt:now}}});
 }
 if(path==='me'&&method==='DELETE'){
  const owner=await getOwner(uid);await db.batch([db.prepare('DELETE FROM scout_runs WHERE account_id=?').bind(uid),db.prepare('DELETE FROM interests WHERE initiator_id=? OR target_id=?').bind(uid,owner?.profile.id||''),db.prepare('DELETE FROM blocks WHERE account_id=? OR target_id=?').bind(uid,owner?.profile.id||''),db.prepare('DELETE FROM profiles WHERE account_id=?').bind(uid),db.prepare("UPDATE scout_runs SET data=json_set(data,'$.profiles',json('[]'),'$.shortlist',json('[]'),'$.status','empty') WHERE mode='live' AND EXISTS (SELECT 1 FROM json_each(scout_runs.data,'$.profiles') AS p WHERE json_extract(p.value,'$.id')=?)").bind(owner?.profile.id||'')]);return json({deleted:true});
 }
 if(path==='scout-runs'&&method==='POST'){
  const body=await req.json() as {intention:Intention;engine?:string;demoOnly?:boolean};if(!['friend','lover'].includes(body.intention))throw new AppError('INVALID_INTENTION','Choose Friend or Lover.');
  const existingOwner=await getOwner(uid);const previewOnly=!existingOwner&&body.demoOnly===true;if(!previewOnly)requireActive(existingOwner,body.intention);const owner=existingOwner;const mode=owner?.profile.mode||'demo';const useAI=mode==='live'||body.engine==='live-ai';
  if(useAI&&!env.OPENAI_API_KEY)throw new AppError('LIVE_SCOUT_NOT_CONFIGURED','Live AI scouting is not configured yet. Your profile is saved; the scripted demo remains available.',503);
  if(useAI&&mode==='live'&&!owner!.settings.allowEvidence)throw new AppError('AI_CONSENT_REQUIRED','Approve your non-sensitive scout brief and selected evidence for AI use in My profile first.',409);
  const recent=await db.prepare('SELECT created_at FROM scout_runs WHERE account_id=? ORDER BY created_at DESC LIMIT 1').bind(uid).first<{created_at:string}>();if(useAI&&recent&&Date.now()-Date.parse(recent.created_at)<10000)throw new AppError('SCOUT_RATE_LIMIT','Give this brief a few seconds before asking your scout again.',429);
  const blockList=await db.prepare('SELECT target_id FROM blocks WHERE account_id = ?').bind(uid).all<{target_id:string}>();
  const candidates=mode==='demo'?demoProfiles.filter(p=>p.intentions.includes(body.intention)&&!blockList.results.some(b=>b.target_id===p.id)).slice(0,12):(await eligibleProfiles(uid,owner!,body.intention)).filter(c=>c.settings.allowEvidence).map(c=>publicProfile(c.profile));
  const runId=crypto.randomUUID();if(useAI){const day=now.slice(0,10);const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('coffee-meets-codex:'+uid));const accountKey=Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,'0')).join('');await db.prepare('DELETE FROM scout_usage WHERE day<?').bind(day).run();const gate=await db.prepare('INSERT INTO scout_usage (id,account_key,day) SELECT ?,?,? WHERE (SELECT COUNT(*) FROM scout_usage WHERE account_key=? AND day=?)<10 AND (SELECT COUNT(*) FROM scout_usage WHERE day=?)<100').bind(runId,accountKey,day,accountKey,day,day).run();if(!gate.meta.changes)throw new AppError('SCOUT_DAILY_LIMIT','The prototype reached its daily AI budget. Please return tomorrow; your profile is safe.',429);const pending={id:runId,intention:body.intention,mode,status:'running',timestamp:now,runtime:'Live scout in progress',engine:'live-ai',shortlist:[],profiles:[]};await db.prepare('INSERT INTO scout_runs (id,account_id,intention,mode,data,created_at) VALUES (?,?,?,?,?,?)').bind(runId,uid,body.intention,mode,JSON.stringify(pending),now).run();}
  let ai:Awaited<ReturnType<typeof boundedScout>>|null=null;if(useAI)try{ai=await boundedScout({apiKey:env.OPENAI_API_KEY!,model:env.OPENAI_MODEL||'gpt-4.1-mini',profiles:candidates,intention:body.intention,brief:mode==='demo'?'Fictional scenario: find curious adult makers with thoughtful projects, creative interests, and a gentle conversation starter.':owner!.settings.scoutBrief,synthetic:mode==='demo'});}catch(e){await db.prepare('UPDATE scout_runs SET data=? WHERE id=? AND account_id=?').bind(JSON.stringify({id:runId,intention:body.intention,mode,status:'failed',timestamp:now,runtime:'Live AI request failed. No scripted result substituted.',engine:'live-ai',shortlist:[],profiles:[]}),runId,uid).run();if(e instanceof ScoutError)throw new AppError(e.code,e.message,503);throw e;}
  const shortlist=ai?ai.shortlist:candidates.slice(0,3).map(p=>demoRecommendation(p,body.intention));
  const run:ScoutRun={id:runId,intention:body.intention,mode,status:shortlist.length?'complete':'empty',timestamp:now,runtime:ai?(ai.apiCalls?`Live OpenAI Responses · ${ai.model} · ${ai.toolCalls} bounded tool calls`:'No eligible approved evidence · no model call'):'Scripted demonstration · no live AI call',engine:ai?'live-ai':'scripted',...(ai?{model:ai.model,toolCalls:ai.toolCalls,apiCalls:ai.apiCalls,durationMs:ai.durationMs,usage:{inputTokens:ai.inputTokens,outputTokens:ai.outputTokens}}:{}),shortlist,profiles:candidates.filter(p=>shortlist.some(r=>r.candidateId===p.id))};
  if(useAI)await db.prepare('UPDATE scout_runs SET data=? WHERE id=? AND account_id=?').bind(JSON.stringify(run),run.id,uid).run();else await db.prepare('INSERT INTO scout_runs (id,account_id,intention,mode,data,created_at) VALUES (?,?,?,?,?,?)').bind(run.id,uid,run.intention,run.mode,JSON.stringify(run),now).run();return json({run:await visibleRun(run,uid)});
 }
 if(path.startsWith('scout-runs/')&&method==='GET'){const id=path.split('/')[1];const row=await db.prepare('SELECT data FROM scout_runs WHERE id=? AND account_id=?').bind(id,uid).first<{data:string}>();if(!row)throw new AppError('NOT_FOUND','This brief is unavailable.',404);return json({run:await visibleRun(JSON.parse(row.data),uid)});}
 if(path==='scout-runs'&&method==='GET'){const row=await db.prepare('SELECT data FROM scout_runs WHERE account_id=? ORDER BY created_at DESC LIMIT 1').bind(uid).first<{data:string}>();return json({run:row?await visibleRun(JSON.parse(row.data),uid):null});}
 if(path.startsWith('profiles/')&&method==='GET'){
  const id=path.split('/')[1];const demo=demoProfiles.find(p=>p.id===id);if(demo)return json({profile:demo});const owner=await getOwner(uid);if(owner?.profile.id===id)return json({profile:publicProfile(owner.profile)});
  if(!owner)throw new AppError('SETUP_REQUIRED','Finish setup first.',409);const candidates=await eligibleProfiles(uid,owner,owner.settings.selectedIntention);const p=candidates.find(p=>p.profile.id===id);if(!p)throw new AppError('NOT_FOUND','This profile is no longer available.',404);return json({profile:publicProfile(p.profile)});
 }
 if(path==='interests'&&method==='POST'){
  const b=await req.json() as {targetId:string;intention:Intention};if(!['friend','lover'].includes(b.intention))throw new AppError('INVALID_INTENTION','Choose Friend or Lover.');const owner=requireActive(await getOwner(uid),b.intention);
  let target:Profile|undefined;if(owner.profile.mode==='demo')target=demoProfiles.find(p=>p.id===b.targetId&&p.intentions.includes(b.intention));else target=(await eligibleProfiles(uid,owner,b.intention)).find(p=>p.profile.id===b.targetId)?.profile;
  if(!target)throw new AppError('NOT_ELIGIBLE','This connection is not eligible or has paused discovery.',409);
  const blocked=await db.prepare('SELECT id FROM blocks WHERE account_id=? AND target_id=?').bind(uid,target.id).first();if(blocked)throw new AppError('BLOCKED','You blocked this profile.',409);
  const id=crypto.randomUUID();await db.prepare('INSERT INTO interests (id,initiator_id,target_id,intention,mode,state,initiator_approved,target_approved,simulated,created_at,updated_at) VALUES (?,?,?,?,?,\'pending\',1,0,0,?,?) ON CONFLICT(initiator_id,target_id,intention,mode) DO UPDATE SET state=CASE WHEN interests.state=\'withdrawn\' THEN \'pending\' ELSE interests.state END,initiator_approved=1,updated_at=excluded.updated_at').bind(id,uid,target.id,b.intention,owner.profile.mode,now,now).run();return json({saved:true,state:'pending'});
 }
 if(path==='interests'&&method==='GET'){
  const owner=await getOwner(uid);const rows=await db.prepare('SELECT * FROM interests WHERE initiator_id=? OR target_id=? ORDER BY updated_at DESC').bind(uid,owner?.profile.id||'').all<Record<string,unknown>>();
  const values=[];for(const r of rows.results){let p=demoProfiles.find(p=>p.id===r.target_id);const incoming=r.initiator_id!==uid;if(!p&&owner&&owner.profile.mode==='live'){const allowed=await eligibleProfiles(uid,owner,String(r.intention));const candidate=allowed.find(c=>incoming?c.accountId===r.initiator_id:c.profile.id===r.target_id);if(candidate)p=publicProfile(candidate.profile);}values.push({id:r.id,targetId:r.target_id,intention:r.intention,mode:r.mode,state:r.state,initiatorApproved:!!r.initiator_approved,targetApproved:!!r.target_approved,simulated:!!r.simulated,createdAt:r.created_at,updatedAt:r.updated_at,profile:p,incoming});}return json({interests:values});
 }
 if(path.startsWith('interests/')&&method==='PATCH'){
  const id=path.split('/')[1];const b=await req.json() as {action:string};const owner=await getOwner(uid);const row=await db.prepare('SELECT * FROM interests WHERE id=?').bind(id).first<Record<string,unknown>>();if(!row||(row.initiator_id!==uid&&row.target_id!==owner?.profile.id))throw new AppError('NOT_FOUND','This introduction is unavailable.',404);
  if(b.action==='withdraw'){await db.prepare('UPDATE interests SET state=\'withdrawn\',initiator_approved=0,target_approved=0,simulated=0,updated_at=? WHERE id=?').bind(now,id).run();return json({saved:true});}
  if(b.action==='simulate'&&row.mode==='demo'&&row.initiator_id===uid&&row.state==='pending'){const result=await db.prepare('UPDATE interests SET state=\'mutual\',target_approved=1,simulated=1,updated_at=? WHERE id=? AND state=\'pending\' AND initiator_approved=1').bind(now,id).run();if(!result.meta.changes)throw new AppError('STATE_CHANGED','This introduction changed. Refresh before trying again.',409);return json({saved:true,simulated:true});}
  if(row.mode==='live'&&row.target_id===owner?.profile.id&&row.state==='pending'&&['accept','decline'].includes(b.action)){
   requireActive(owner,String(row.intention));const candidates=await eligibleProfiles(uid,owner!,String(row.intention));if(!candidates.some(c=>c.accountId===row.initiator_id))throw new AppError('NOT_ELIGIBLE','Consent or eligibility has changed.',409);
   const result=await db.prepare('UPDATE interests SET state=?,target_approved=?,updated_at=? WHERE id=? AND state=\'pending\' AND initiator_approved=1').bind(b.action==='accept'?'mutual':'declined',b.action==='accept'?1:0,now,id).run();if(!result.meta.changes)throw new AppError('STATE_CHANGED','This introduction changed. Refresh before trying again.',409);return json({saved:true});
  }throw new AppError('ACTION_NOT_ALLOWED','Only each participant can approve their own side.',403);
 }
 if(path==='blocks'&&method==='POST'){const b=await req.json() as {targetId:string;reason?:string};if(!b.targetId||b.targetId.length>100)throw new AppError('INVALID_TARGET','Choose a profile.');await db.prepare('INSERT INTO blocks (id,account_id,target_id,reason,created_at) VALUES (?,?,?,?,?) ON CONFLICT(account_id,target_id) DO NOTHING').bind(crypto.randomUUID(),uid,b.targetId,(b.reason||'').slice(0,400),now).run();const me=await getOwner(uid);await db.prepare('UPDATE interests SET state=\'withdrawn\',initiator_approved=0,target_approved=0,updated_at=? WHERE (initiator_id=? AND target_id=?) OR (target_id=? AND initiator_id IN (SELECT account_id FROM profiles WHERE profile_id=?))').bind(now,uid,b.targetId,me?.profile.id||'',b.targetId).run();return json({saved:true});}
 throw new AppError('NOT_FOUND','This page could not be found.',404);
 }catch(error){if(error instanceof AppError)return json({error:{code:error.code,message:error.message,retryable:error.status>=500,requestId:crypto.randomUUID()}},error.status);console.error('Coffee request failed',error instanceof Error?error.name:'unknown');return json({error:{code:'UNAVAILABLE',message:'We could not save or load this right now. Your draft is still here. Please try again.',retryable:true,requestId:crypto.randomUUID()}},503);}}
export const GET=handle;export const PUT=handle;export const POST=handle;export const PATCH=handle;export const DELETE=handle;
