import type {Profile, Recommendation, Intention} from './types';
const date='2026-10-04';
const ev=(id:string,kind:'project'|'interest'|'metric',title:string,description:string,extra={})=>({id,kind,title,description,url:'',provenance:'syntheticDemo' as const,asOf:date,visible:true,scoutUse:true,...extra});
export const demoProfiles:Profile[]=[
{id:'demo-mika',mode:'demo',displayName:'Mika',headline:'Making room for little adventures.',introduction:'Part designer, part sidewalk explorer. I make tiny tools for a slower, more curious life. Tell me about the last thing you made just because.',chatgptProfileUrl:'',sharingSelfAttested:false,intentions:['friend','lover'],status:'demoOnly',location:'Taipei · open to online',gender:'Woman',genderVisibility:'public',avatar:'tracy',tags:['Creative coding','City walks','Good coffee'],featuredEvidenceId:'mika-project',ageLabel:'Fictional adult · 28',palette:'sage',evidence:[ev('mika-project','project','The Sidewalk Club','A tiny walking journal that turns a familiar neighborhood into a new adventure.'),ev('mika-interest','interest','One new street a day','Collecting quiet corners, leafy lanes and very good coffee.'),ev('mika-tokens','metric','Curiosity, in tokens','A fictional owner-supplied usage snapshot. Not a measure of talent, wealth or compatibility.',{value:'12.8M',unit:'lifetime tokens',coverage:'Illustrative total · not connected to an account'})]},
{id:'demo-jules',mode:'demo',displayName:'Jules',headline:'A little code. A lot of color.',introduction:'I build playful experiments for people who think they are not creative. Looking for someone to trade unfinished ideas with, over a very finished coffee.',chatgptProfileUrl:'',sharingSelfAttested:false,intentions:['friend','lover'],status:'demoOnly',location:'Singapore · online & long-distance',gender:'Nonbinary',genderVisibility:'mystery',avatar:'initials',tags:['Generative art','Open source','Music'],featuredEvidenceId:'jules-project',ageLabel:'Fictional adult · 30',palette:'lavender',evidence:[ev('jules-project','project','Small Joy Machine','An interactive canvas that turns a few everyday sounds into colorful patterns.'),ev('jules-interest','interest','Make something on Sundays','A small habit of sharing works in progress rather than waiting for perfect.'),ev('jules-tokens','metric','A building rhythm','Optional activity evidence, shared by this fictional owner.',{value:'47',unit:'building days',coverage:'Past 90 days · illustrative'})]},
{id:'demo-noah',mode:'demo',displayName:'Noah',headline:'Tools for things worth remembering.',introduction:'Developer, notebook collector, enthusiastic beginner at pottery. I like small projects that help people find a little more time for each other.',chatgptProfileUrl:'',sharingSelfAttested:false,intentions:['friend'],status:'demoOnly',location:'Taipei · local & online',gender:'Man',genderVisibility:'public',avatar:'initials',tags:['Useful tools','Notebooks','Ceramics'],featuredEvidenceId:'noah-project',ageLabel:'Fictional adult · 32',palette:'peach',evidence:[ev('noah-project','project','Good Things, Kept','A private collection of little notes, places and moments to return to.'),ev('noah-interest','interest','The best café has no rush','A shared table, a notebook, and time to follow an idea.')]},
{id:'demo-robin',mode:'demo',displayName:'Robin',headline:'Always learning something by hand.',introduction:'I make helpful websites and occasionally unhelpful ceramics. Curious about people with a project they cannot stop talking about.',chatgptProfileUrl:'',sharingSelfAttested:false,intentions:['lover'],status:'demoOnly',location:'Taipei · local & online',gender:'Woman',genderVisibility:'public',avatar:'initials',tags:['Web experiments','Ceramics','Slow weekends'],featuredEvidenceId:'robin-project',ageLabel:'Fictional adult · 29',palette:'peach',evidence:[ev('robin-project','project','Weekend Almanac','A small collection of creative rituals to make weekends feel a little longer.'),ev('robin-interest','interest','Curiosity over credentials','Making space for beginners and conversations without a checklist.')]}];
export function demoRecommendation(p:Profile,intention:Intention):Recommendation {const e=p.evidence.filter(e=>e.visible&&e.scoutUse);return {candidateId:p.id,reasons:[{text:`${p.displayName} turns curiosity into small, thoughtful projects. “${e[0].title}” is a natural place to start a conversation.`,evidenceIds:[e[0].id]},{text:intention==='friend'?`Your interest in making things meets ${p.displayName}’s ${p.tags[0].toLowerCase()} and ${p.tags[1].toLowerCase()}. There is something here to explore together.`:`You both chose Lover in this fictional scenario. ${e[1]?.title || p.tags[1]} suggests a low-pressure first conversation.`,evidenceIds:[e[1]?.id||e[0].id]}],uncertainty:'Shared interests are a starting point. Chemistry, availability and real-world fit are still unknown.',opener:`I liked the idea behind ${e[0].title}. What first made you want to build it?`};}
