import { z } from 'zod';
import { database } from '../db';
import type {Profile,Settings} from './types';
export class AppError extends Error { constructor(public code:string, message:string,public status=400){super(message);} }
const url=z.string().max(1000).refine(v=>{if(!v)return true;try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}},'Use a full https:// link.');
const evidence=z.object({id:z.string().min(1).max(100),kind:z.enum(['project','interest','metric','social']),title:z.string().min(1).max(100),description:z.string().max(600),url,provenance:z.literal('ownerSupplied').default('ownerSupplied'),asOf:z.string().max(30),visible:z.boolean(),scoutUse:z.boolean(),value:z.string().max(40).nullable().optional(),unit:z.string().max(60).optional(),coverage:z.string().max(150).optional()});
export const saveSchema=z.object({profile:z.object({displayName:z.string().trim().min(1).max(50),headline:z.string().max(100),introduction:z.string().max(280),chatgptProfileUrl:url.refine(v=>{try{const u=new URL(v);return ['chatgpt.com','www.chatgpt.com'].includes(u.hostname)&&/^\/u\/[^/]+\/?$/.test(u.pathname)&&!u.search&&!u.hash;}catch{return false;}},'Enter your ChatGPT public profile, such as https://chatgpt.com/u/your-handle.'),sharingSelfAttested:z.literal(true),mode:z.enum(['demo','live']),intentions:z.array(z.enum(['friend','lover'])).min(1).max(2),status:z.enum(['available','paused','demoOnly']),location:z.string().max(100),gender:z.string().max(60),genderVisibility:z.enum(['public','mystery','hidden']),avatar:z.enum(['owen','tracy','initials']),tags:z.array(z.string().max(35)).max(6),evidence:z.array(evidence).max(8),featuredEvidenceId:z.string().max(100)}),settings:z.object({adultDeclaration:z.literal(true),discoveryConsent:z.boolean(),consentVersion:z.literal('2026-10-04'),selectedIntention:z.enum(['friend','lover']),preferredGenders:z.array(z.string().max(60)).max(8),connectionStyle:z.array(z.enum(['local','online','long-distance'])).min(1).max(3),language:z.string().max(80),scoutBrief:z.string().max(500),allowEvidence:z.boolean(),updatedAt:z.string().optional()})});
export type Stored={profile:Profile;settings:Settings};
export async function getOwner(accountId:string):Promise<Stored|null>{const row=await database().prepare('SELECT data, settings FROM profiles WHERE account_id = ?').bind(accountId).first<{data:string;settings:string}>();return row?{profile:JSON.parse(row.data),settings:JSON.parse(row.settings)}:null;}
export function publicProfile(p:Profile):Profile {return {id:p.id,mode:p.mode,displayName:p.displayName,headline:p.headline,introduction:p.introduction,chatgptProfileUrl:p.chatgptProfileUrl,sharingSelfAttested:p.sharingSelfAttested,intentions:p.intentions,status:p.status,location:p.location,gender:p.genderVisibility==='public'?p.gender:'',genderVisibility:p.genderVisibility,avatar:p.avatar,tags:p.tags,evidence:p.evidence.filter(e=>e.visible).map(e=>({...e})),featuredEvidenceId:p.featuredEvidenceId,ageLabel:p.ageLabel,palette:p.palette};}
export function mutuallyEligible(a:Stored,b:Stored,intention:string){return a.profile.id!==b.profile.id&&a.profile.mode==='live'&&b.profile.mode==='live'&&a.profile.status==='available'&&b.profile.status==='available'&&a.settings.adultDeclaration&&b.settings.adultDeclaration&&a.settings.discoveryConsent&&b.settings.discoveryConsent&&a.profile.intentions.includes(intention as any)&&b.profile.intentions.includes(intention as any)&&(!a.settings.preferredGenders.length||a.settings.preferredGenders.includes(b.profile.gender))&&(!b.settings.preferredGenders.length||b.settings.preferredGenders.includes(a.profile.gender))&&a.settings.connectionStyle.some(v=>b.settings.connectionStyle.includes(v))&&a.settings.language.toLowerCase()===b.settings.language.toLowerCase();}
export async function eligibleProfiles(accountId:string,owner:Stored,intention:string){const result=await database().prepare('SELECT account_id, data, settings FROM profiles WHERE account_id != ? LIMIT 100').bind(accountId).all<{account_id:string;data:string;settings:string}>();const blocked=await database().prepare('SELECT target_id FROM blocks WHERE account_id = ? UNION SELECT p.profile_id AS target_id FROM blocks b JOIN profiles p ON p.account_id=b.account_id WHERE b.target_id=?').bind(accountId,owner.profile.id).all<{target_id:string}>();const blockIds=new Set(blocked.results.map(x=>x.target_id));return result.results.map(r=>({accountId:r.account_id,profile:JSON.parse(r.data) as Profile,settings:JSON.parse(r.settings) as Settings})).filter(x=>!blockIds.has(x.profile.id)&&mutuallyEligible(owner,x,intention)).slice(0,12);}
export function requireActive(owner:Stored|null,intention?:string){if(!owner||!owner.settings.adultDeclaration)throw new AppError('SETUP_REQUIRED','Finish your profile and adult declaration first.',409);if(intention&&!owner.profile.intentions.includes(intention as any))throw new AppError('INTENTION_NOT_SELECTED','Choose this intention in your profile first.',409);if(owner.profile.mode==='live'&&(!owner.settings.discoveryConsent||owner.profile.status!=='available'))throw new AppError('DISCOVERY_PAUSED','Your discovery is paused. Resume it in your profile to continue.',409);return owner;}
