import urllib.request,urllib.error,json,sys,uuid
base='http://127.0.0.1:8787'; results=[]; prefix='test-'+uuid.uuid4().hex[:8]+'-'
def req(path,method='GET',data=None,identity=None):
 h={'Content-Type':'application/json'}
 if identity:h.update({'oai-authenticated-user-id':prefix+identity,'oai-authenticated-user-email':prefix+identity+'@test.invalid'})
 request=urllib.request.Request(base+path,data=json.dumps(data).encode() if data is not None else None,headers=h,method=method)
 try:
  r=urllib.request.urlopen(request);return r.status,json.load(r)
 except urllib.error.HTTPError as e:return e.code,json.load(e)
def check(name, condition):
 results.append({'test':name,'passed':bool(condition)});print(('PASS ' if condition else 'FAIL ')+name)
def owner(name,mode='demo',gender='Woman'):
 return {'profile':{'displayName':name,'headline':'Local test fixture','introduction':'Only a local test.','chatgptProfileUrl':'https://chatgpt.com/u/local-test-only','sharingSelfAttested':True,'mode':mode,'intentions':['friend','lover'],'status':'available' if mode=='live' else 'demoOnly','location':'Local test','gender':gender,'genderVisibility':'mystery','avatar':'owen','tags':['Building'],'evidence':[{'id':'test-e1','kind':'project','title':'Test project','description':'A local fixture','url':'','provenance':'ownerSupplied','asOf':'2026-10-04','visible':True,'scoutUse':True},{'id':'hidden','kind':'interest','title':'PRIVATE EVIDENCE','description':'Must not appear','url':'','provenance':'ownerSupplied','asOf':'2026-10-04','visible':False,'scoutUse':False}],'featuredEvidenceId':'test-e1'},'settings':{'adultDeclaration':True,'discoveryConsent':mode=='live','consentVersion':'2026-10-04','selectedIntention':'friend','preferredGenders':[],'connectionStyle':['online'],'language':'English','scoutBrief':'Shared creative interests.','allowEvidence':True}}
check('signed-out writes rejected',req('/api/me','PUT',owner('A'))[0]==401)
a=owner('Local A');status,d=req('/api/me','PUT',a,'local-a');check('owner save in D1',status==200);aid=d['owner']['profile']['id'];check('save persists after reload',req('/api/me',identity='local-a')[1]['owner']['profile']['displayName']=='Local A');check('owner isolation',req('/api/me',identity='local-b')[1]['owner'] is None)
status,run=req('/api/scout-runs','POST',{'intention':'friend'},'local-a');check('Friend demo returns three',status==200 and len(run['run']['profiles'])==3);rid=run['run']['id'];check('run ownership enforced',req('/api/scout-runs/'+rid,identity='local-b')[0]==404)
status,run=req('/api/scout-runs','POST',{'intention':'lover'},'local-a');check('Lover demo filters Friend-only fixture',status==200 and all(p['id']!='demo-noah' for p in run['run']['profiles']));check('honest scripted provenance','Scripted' in run['run']['runtime']);
req('/api/interests','POST',{'targetId':'demo-mika','intention':'friend'},'local-a');req('/api/interests','POST',{'targetId':'demo-mika','intention':'friend'},'local-a');ints=req('/api/interests',identity='local-a')[1]['interests'];check('interest idempotency',len(ints)==1);iid=ints[0]['id'];check('pending does not imply mutual',ints[0]['state']=='pending' and not ints[0]['targetApproved']);check('other identity cannot approve demo',req('/api/interests/'+iid,'PATCH',{'action':'simulate'},'local-b')[0]==404);req('/api/interests/'+iid,'PATCH',{'action':'simulate'},'local-a');i=req('/api/interests',identity='local-a')[1]['interests'][0];check('second approval explicitly simulated',i['state']=='mutual' and i['simulated']);req('/api/interests/'+iid,'PATCH',{'action':'withdraw'},'local-a');check('withdraw clears both approvals',all(not req('/api/interests',identity='local-a')[1]['interests'][0][f] for f in ['initiatorApproved','targetApproved']));
a=owner('Live test A','live','Man');b=owner('Live test B','live','Woman');req('/api/me','PUT',a,'live-a');db=req('/api/me','PUT',b,'live-b')[1];bid=db['owner']['profile']['id'];aid=req('/api/me',identity='live-a')[1]['owner']['profile']['id'];check('live scout honest configuration failure',req('/api/scout-runs','POST',{'intention':'friend'},'live-a')[0]==503);check('no self match',req('/api/interests','POST',{'targetId':aid,'intention':'friend'},'live-a')[0]==409)
status,pub=req('/api/profiles/'+bid,identity='live-a');check('public projection excludes hidden evidence and gender',status==200 and pub['profile']['gender']=='' and all(e['id']!='hidden' for e in pub['profile']['evidence']));req('/api/interests','POST',{'targetId':bid,'intention':'friend'},'live-a');ii=req('/api/interests',identity='live-a')[1]['interests'][0]['id'];check('initiator cannot approve other side',req('/api/interests/'+ii,'PATCH',{'action':'accept'},'live-a')[0]==403);check('recipient independently approves',req('/api/interests/'+ii,'PATCH',{'action':'accept'},'live-b')[0]==200);check('mutual state uses two approvals',req('/api/interests',identity='live-a')[1]['interests'][0]['state']=='mutual');check('recipient can withdraw',req('/api/interests/'+ii,'PATCH',{'action':'withdraw'},'live-b')[0]==200)
req('/api/interests','POST',{'targetId':bid,'intention':'friend'},'live-a');req('/api/interests/'+ii,'PATCH',{'action':'accept'},'live-b');req('/api/blocks','POST',{'targetId':aid,'reason':'Local test'},'live-b');a_int=req('/api/interests',identity='live-a')[1]['interests'][0];check('block withdraws incoming mutual',a_int['state']=='withdrawn');check('block hides counterpart latest profile',not a_int.get('profile'));check('blocked new interest rejected',req('/api/interests','POST',{'targetId':bid,'intention':'friend'},'live-a')[0]==409)
c=owner('Live C','live','Woman');d=owner('Live D','live','Man');c['settings']['preferredGenders']=['Woman'];req('/api/me','PUT',c,'live-c');did=req('/api/me','PUT',d,'live-d')[1]['owner']['profile']['id'];check('reciprocal hard preferences enforced',req('/api/interests','POST',{'targetId':did,'intention':'lover'},'live-c')[0]==409)
with open('outputs/api-test-results.json','w') as f:json.dump(results,f,indent=2)
print(str(sum(r['passed'] for r in results))+'/'+str(len(results))+' passed');sys.exit(0 if all(r['passed'] for r in results) else 1)
